# Asymmetrica Protocol Quality Gates - Pre-Commit Hooks
# Enforces protocol compliance before commits

repos:
  # Standard Python code quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=100']

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '100']

  # Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--extend-ignore=E203,W503']

  # Asymmetrica Protocol Compliance Checker (CUSTOM)
  - repo: local
    hooks:
      - id: asymmetrica-protocol-compliance
        name: Asymmetrica Protocol Compliance
        entry: python scripts/check_protocol_compliance.py
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
        verbose: true

      - id: asymmetrica-validation-level
        name: Check Validation Levels (@validation)
        entry: python scripts/check_protocol_compliance.py --check-validation
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: asymmetrica-performance-targets
        name: Check Performance Targets (@performance)
        entry: python scripts/check_protocol_compliance.py --check-performance
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: asymmetrica-complexity-annotations
        name: Check Complexity Annotations (@complexity)
        entry: python scripts/check_protocol_compliance.py --check-complexity
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--no-strict-optional']
        additional_dependencies: ['types-PyYAML']

# Quality Gate Thresholds:
# - Asymmetrica Protocol Compliance: 100% (blocks commit if fails)
# - Stabilization Tests: 100% pass required
# - Optimization Tests: 85% pass required
# - Exploration Tests: 70% pass required

# Installation:
# 1. Install pre-commit: pip install pre-commit
# 2. Install hooks: pre-commit install
# 3. Run manually: pre-commit run --all-files

# Skip hooks temporarily (emergency only):
# git commit --no-verify -m "Emergency fix"
